### ISSUE TITLE
Ingress not conneting to domain

### ISSUE THREAD

**Issue by francesco-di-marcantonio** [PHOENIX-MEDIA/magento2-helm#10]
Hi there, so finally we deployed the infrastructure. Now we are trying to connect to application but the ingress is not managing the domain.

we changed values  in this files:

+++ values

ingress:
  ## Set to true to enable ingress record generation
  enabled: true
  # ingressClassName: nginx
  certManager: true
  useProxyProtocol: true
  annotations: {}
 

    ## The list of hostnames to be covered with this ingress record.
    ## Most likely this will be just one host, but in the event more hosts are needed, this is an array
  hosts:
    - name: domain.it
      paths:
        - path: "/"
          serviceName: varnish
          servicePort: 80
          tls: true
    ## Set this to true in order to enable TLS on the ingress record
    #    tls: true

    ## Optionally specify the TLS hosts for the ingress record
    ## Useful when the Ingress controller supports www-redirection
  ## If not specified, the above host name will be used
#    tlsHosts:
    - domain.i

#    tlsSecret: site-cert

+++values_gke

managedCert:
  enabled: true
  domains:
    - iride.dimarcanton.io
    
ingress:
  enabled: true
  certManager: true
  hosts:
# Uncomment this section and update with your values
    - name: domain.it
      paths:
      - path: "/"
        serviceName: varnish
        servicePort: 8080

`k get ingress`

return this:

`NAME      CLASS    HOSTS                  ADDRESS         PORTS   AGE
magento   <none>   domain.it   34.149.75.162   80      2d4h
`

the application looks deployed but we receive 

Error: Client network socket disconnected before secure TLS connection was established

for https

and no answer for http

**Comment by francesco-di-marcantonio** [comment]
Adding some images from console
![Schermata del 2024-01-11 18-43-49](https://github.com/PHOENIX-MEDIA/magento2-helm/assets/98045367/da44ff46-1079-4730-91fb-66f3888b64be)

![Schermata del 2024-01-11 18-42-41](https://github.com/PHOENIX-MEDIA/magento2-helm/assets/98045367/02a10d60-69cf-433e-8614-b23bf59678d2)

![Schermata del 2024-01-11 18-43-59](https://github.com/PHOENIX-MEDIA/magento2-helm/assets/98045367/f282f793-08ac-4bea-82bc-3231222ca967)

**Comment by francesco-di-marcantonio** [comment]
From inside the container if we ping the host we receive no answer.

(but the host is correctly redirecting to the internal ip)

![Schermata del 2024-01-11 18-48-13](https://github.com/PHOENIX-MEDIA/magento2-helm/assets/98045367/e14ab53c-171a-4bf0-ae3d-47eed68bb5f2)

**Comment by phoenix-bjoern** [comment]
@francesco-di-marcantonio Ingress configuration varies on managed K8S services. Check the K8S provider's documentation on how to configure incoming traffic and if ingress is managed outside of K8S.
In the ingress configuration always reference the service `varnish` or `magento`, never the pod or deployment.

`ping` usually doesn't work with K8S services. Use `nslookup magento` instead. It should resolve the service IP.
