### ISSUE TITLE
Please provide K8s manifest files along with how to install magento on php-nginx image, so that I can be used directly on K8S

### ISSUE THREAD

**Issue by Naveen-LinuxAwsguy** [PHOENIX-MEDIA/magento2-helm#16]

**Comment by phoenix-bjoern** [comment]
@Naveen-LinuxAwsguy: `helm template .`

**Comment by Naveen-LinuxAwsguy** [comment]
Can you please provide document on how to install magento on nginx & PHP and the deployment script, i saw it was a bit confusing please help

**Comment by phoenix-bjoern** [comment]
@Naveen-LinuxAwsguy the Helm chart ships with a Docker container which exactly does that!?

Here is a repo to build Magento2 from scratch: https://github.com/PHOENIX-MEDIA/magento2-build

Maybe read more about the concepts in my Medium series: https://medium.com/@bjoern.kraus/running-magento2-in-kubernetes-part-3-deploying-the-application-68275f56098
